plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.logging.markers', 'REGISTRIES'
            systemProperty 'neoforge.logging.console.level', 'debug'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        gameTestServer {
            type = 'gameTestServer'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    mavenCentral()
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases/'
    }
    maven {
        name = 'Curios'
        url = 'https://maven.theillusivec4.top/'
    }
    maven {
        name = 'Shedaniel'
        url = 'https://maven.shedaniel.me/'
    }
    maven {
        name = 'Create'
        url = 'https://maven.createmod.net'
    }
    maven {
        name = 'Registrate'
        url = 'https://maven.ithundxr.dev/snapshots'
    }
}

dependencies {
    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
    localRuntime "top.theillusivec4.curios:curios-neoforge:${curios_version}"
    implementation "me.shedaniel.cloth:cloth-config-neoforge:15.0.140"
    compileOnly("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
}
tasks.named('processResources', ProcessResources).configure {
    from('Assets') {
        include 'mod_logo.png'
    }

    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
