org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Minecraft & NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,]
neo_version=21.1.62
neo_version_range=[21.1.0,)
loader_version_range=[4,)

# Mappings
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Mod Info
mod_id=thinair
mod_name=ThinAir-Relived
mod_license=MIT
mod_version=1.0.5
mod_group_id=dev.maire.thinairrelived
mod_authors=Marie
mod_description=A clean NeoForge 1.21.1 port of Thin Air by fuzs Ported by Marie.

# Dependencies
curios_version=9.5.1+1.21.1
create_version=6.0.10-280